# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ci20/wiringX

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ci20/wiringX

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ci20/wiringX/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ci20/wiringX/CMakeFiles /home/ci20/wiringX/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ci20/wiringX/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sources

# Build rule for target.
sources: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sources
.PHONY : sources

# fast build rule for target.
sources/fast:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/build
.PHONY : sources/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named wiringx_shared

# Build rule for target.
wiringx_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wiringx_shared
.PHONY : wiringx_shared

# fast build rule for target.
wiringx_shared/fast:
	$(MAKE) -f CMakeFiles/wiringx_shared.dir/build.make CMakeFiles/wiringx_shared.dir/build
.PHONY : wiringx_shared/fast

#=============================================================================
# Target rules for targets named wiringx_static

# Build rule for target.
wiringx_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wiringx_static
.PHONY : wiringx_static

# fast build rule for target.
wiringx_static/fast:
	$(MAKE) -f CMakeFiles/wiringx_static.dir/build.make CMakeFiles/wiringx_static.dir/build
.PHONY : wiringx_static/fast

bananapi.o: bananapi.c.o
.PHONY : bananapi.o

# target to build an object file
bananapi.c.o:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/bananapi.c.o
.PHONY : bananapi.c.o

bananapi.i: bananapi.c.i
.PHONY : bananapi.i

# target to preprocess a source file
bananapi.c.i:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/bananapi.c.i
.PHONY : bananapi.c.i

bananapi.s: bananapi.c.s
.PHONY : bananapi.s

# target to generate assembly for a file
bananapi.c.s:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/bananapi.c.s
.PHONY : bananapi.c.s

ci20.o: ci20.c.o
.PHONY : ci20.o

# target to build an object file
ci20.c.o:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/ci20.c.o
.PHONY : ci20.c.o

ci20.i: ci20.c.i
.PHONY : ci20.i

# target to preprocess a source file
ci20.c.i:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/ci20.c.i
.PHONY : ci20.c.i

ci20.s: ci20.c.s
.PHONY : ci20.s

# target to generate assembly for a file
ci20.c.s:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/ci20.c.s
.PHONY : ci20.c.s

hummingboard.o: hummingboard.c.o
.PHONY : hummingboard.o

# target to build an object file
hummingboard.c.o:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/hummingboard.c.o
.PHONY : hummingboard.c.o

hummingboard.i: hummingboard.c.i
.PHONY : hummingboard.i

# target to preprocess a source file
hummingboard.c.i:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/hummingboard.c.i
.PHONY : hummingboard.c.i

hummingboard.s: hummingboard.c.s
.PHONY : hummingboard.s

# target to generate assembly for a file
hummingboard.c.s:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/hummingboard.c.s
.PHONY : hummingboard.c.s

radxa.o: radxa.c.o
.PHONY : radxa.o

# target to build an object file
radxa.c.o:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/radxa.c.o
.PHONY : radxa.c.o

radxa.i: radxa.c.i
.PHONY : radxa.i

# target to preprocess a source file
radxa.c.i:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/radxa.c.i
.PHONY : radxa.c.i

radxa.s: radxa.c.s
.PHONY : radxa.s

# target to generate assembly for a file
radxa.c.s:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/radxa.c.s
.PHONY : radxa.c.s

raspberrypi.o: raspberrypi.c.o
.PHONY : raspberrypi.o

# target to build an object file
raspberrypi.c.o:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/raspberrypi.c.o
.PHONY : raspberrypi.c.o

raspberrypi.i: raspberrypi.c.i
.PHONY : raspberrypi.i

# target to preprocess a source file
raspberrypi.c.i:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/raspberrypi.c.i
.PHONY : raspberrypi.c.i

raspberrypi.s: raspberrypi.c.s
.PHONY : raspberrypi.s

# target to generate assembly for a file
raspberrypi.c.s:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/raspberrypi.c.s
.PHONY : raspberrypi.c.s

wiringX.o: wiringX.c.o
.PHONY : wiringX.o

# target to build an object file
wiringX.c.o:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/wiringX.c.o
.PHONY : wiringX.c.o

wiringX.i: wiringX.c.i
.PHONY : wiringX.i

# target to preprocess a source file
wiringX.c.i:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/wiringX.c.i
.PHONY : wiringX.c.i

wiringX.s: wiringX.c.s
.PHONY : wiringX.s

# target to generate assembly for a file
wiringX.c.s:
	$(MAKE) -f CMakeFiles/sources.dir/build.make CMakeFiles/sources.dir/wiringX.c.s
.PHONY : wiringX.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... sources"
	@echo "... uninstall"
	@echo "... wiringx_shared"
	@echo "... wiringx_static"
	@echo "... bananapi.o"
	@echo "... bananapi.i"
	@echo "... bananapi.s"
	@echo "... ci20.o"
	@echo "... ci20.i"
	@echo "... ci20.s"
	@echo "... hummingboard.o"
	@echo "... hummingboard.i"
	@echo "... hummingboard.s"
	@echo "... radxa.o"
	@echo "... radxa.i"
	@echo "... radxa.s"
	@echo "... raspberrypi.o"
	@echo "... raspberrypi.i"
	@echo "... raspberrypi.s"
	@echo "... wiringX.o"
	@echo "... wiringX.i"
	@echo "... wiringX.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

